config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B',
  }

  ORDER_BY = {
    new: "created_at DESC",
    old: "created_at ASC",
    expensive: "price DESC",
    cheap: "price ASC",
  }

  has_one_attached :photo
  validates :title, :description, :price, presence: true
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include Pagy::Backend
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: "Category was successfully created." 
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if category.update(category_params)
      redirect_to categories_url, notice: "Category was successfully updated." 
    else
      fender :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: "Category was successfully destroyed." 

  end

  private
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @categories = Category.order(name: :asc).load_async

    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).
            load_async, items: 12)
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path,
      notice: 'Product added properly'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    product
  end

  def update
    if product.update(product_params)
      redirect_to @product, notice: "Product succesfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy
    redirect_to products_path, notice: "Product properly deleted"

  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end

  def product_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by)
  end

  def product
        @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
   <div>
    <%= category.name %>
    <div>
      <%= link_to "Edit", edit_category_path(category) %>
      <%= link_to "Delete category", category_path(category),
                    data: { turbo_method: :delete, 
                    turbo_confirm: "Are you sure?" } %>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <%= @category.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>

  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= render partial: 'category', collection: @categories %>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do %>
    <%= category.name %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: @product) do |form| %>

  <%= @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>

  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>  
  </div>

  <div>
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name %>
  </div>

  <div>
    <%= form.label :photo %>
    <%= form.file_field :photo %>  
  </div>

  <%= form.submit %>

<% end %>

app/views/products/_product.html.erb
  <%= link_to product_path(product.id), class: 'product', 'data-turbo-frame': '_top' do %>
    <h2><%= product.title %></h2>
    <span><%= product.price %></span>
    <span><%= image_tag product.photo, width: 100 if product.photo.attached? %></span>
  <% end %> 

app/views/products/edit.html.erb
<h1> Edit </h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Products:</h1>

<%= turbo_frame_tag 'home' do %>
    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: "Search",
            OnChange: 'this.form.requestSubmit()',
            value: params[:query_text] %>
        <%= form.number_field :min_price, placeholder: "min price",
            OnChange: 'this.form.requestSubmit()',
            value: params[:min_price] %>
        <%= form.number_field :max_price, placeholder: "max price",
            OnChange: 'this.form.requestSubmit()',
            value: params[:max_price] %>
        <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map { |order| 
            [order, order]}, params[:order_by]), {}, { OnChange: 'this.form.requestSubmit()' } %>
    <% end %>

  <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products' do %>
    <%= render partial: 'product', collection: @products %>
    <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products', loading: :lazy if @pagy.next %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h2>Add Product</h2>

<%= render "form" %>

app/views/products/show.html.erb
<h1 class='title' ><%= @product.title %></h1>
<p class='description' ><%= @product.description %></p>
<p class='price' ><%= number_to_currency(@product.price) %></p>
<span><%= image_tag @product.photo, 
          width: 200 if @product.photo.attached? %></span>

<div>
  <%= link_to "Edit product", edit_product_path(@product) %>
  <%= link_to "Delete product", product_path(@product),
      data: { turbo_method: :delete, 
              turbo_confirm: "Are you sure?" } %>
</div>

app/views/shared/_flash.html.erb
<%= notice %>
<%= alert %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
    <h1>V E N D E L O</h1>
<% end %>

<%= link_to 'Add Product', new_product_path %>
<%= link_to 'All categories', categories_path %>